### ISSUE TITLE
[Feature] Change in OreDict

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopmentMods/MinecraftMineralogy#36]
Maybe a config, to remove cobblestone/sandstone oreDict name, to prevent recipe overlap, and add a recipe to convert MineralogyStone to VanillaCobble instead

**Comment by drakray** [comment]
Also, Nitrate(dustNitrate) is different than Minerals Niter(dustNiter), and Phosphorous(dustPhosphorous) is different than Minerals Phosphorus(dustPhosphorus)?, yet they share resourceBlock texture.

**Comment by SkyBlade1978** [comment]
2 Mineralogy Stone plus 2 Gravel makes Vanilla Cobble, also breaking any Mineralogy stone with a Hammer/Crusher also makes cobble (except Chert which turns directly to gravel), I'll take a look at the other things you mentioned

**Comment by drakray** [comment]
yeah I saw that, but some Mineralogy recipe use for exemple 3 MStone to make slab, but some mod use 3 oreDictCobblestone to make slab, so recipe overlap.
Or some premade custom recipe made with Craftweaker could conflict when trying to use oreDictCobblestone, with recipe added after adding Mineralogy(don't have exemple right now, I had to remove Mineralogy because it made Dense Metal go [WILD](https://github.com/MinecraftModDevelopmentMods/DenseMetals/issues/7) lol)

**Comment by SkyBlade1978** [comment]
hmmm, I made each mineralogy rock register as cobblestone thinking this would improve it's cross mod compatability so that if any recipe called for cobblestone, you could use a mineralogy rock instead, I could go back to the way I think it was before, but as I recall we had a defect raised originally that mineralogy rock wasn't usable as cobblestone in other mods, I think the solution maybe to give it both possible behaviours controllable by a config switch, so it would either more narrowly make its rocks work for existing vanilla recipes but not register them as cobblestone, or register them as cobblestone..  @jriwanek  and @dshadowwolf  any thoughts?

**Comment by drakray** [comment]
I personally used CreatTweaker to remove the cobblestone oreDict name, using rock+gravel=cobblestone for all my cobble needs(I also have a way to make gravel from cobble, so it's just rock/cobble 1/1, without any overlap, though there is some other discrepancy like some recipe not showing in JEI, like rock bricks)

**Comment by SkyBlade1978** [comment]
@drakray I've added a config option to turn off the automatic registration of rock types as cobblestone, hopefully in the next few days that update will make its way into a release

**Comment by SkyBlade1978** [comment]
This has been fixed with a config option and will be in the next release
