### ISSUE TITLE
Minecraft Server Crash

### ISSUE THREAD

**Issue by slitesun** [MinecraftModDevelopmentMods/MinecraftMineralogy#73]
Crash Report: https://pastebin.com/vWkAzda9
Mod list: https://pastebin.com/EF2f9gSE
Version Sponge: spongeforge-1.12.2-2768-7.1.5-RC3543
Version Forge: forge-1.12.2-14.23.5.2768-universal

**Comment by dshadowwolf** [comment]
@SkyBlade1978 this looks to be from early-registration of smelting recipes. It shouldn't matter, but if the smelting recipe goes in before the Item Registration event has completed (or, at least, you've registered it all) (since the code references Items.getItemFromBlock() in the smelting registration) it'll get a null.

**Comment by SkyBlade1978** [comment]
Hi @slitesun , sorry I've been away a while, I'm currently adding some new features to mineralogy so I will try to fix outstanding bugs while I'm at it.  I can't say I've experienced your crash myself so I was wondering, did it happen often?

**Comment by SkyBlade1978** [comment]
This should be fixed in the new release
